version: '3.7'

services:
  php:
    image: ghcr.io/pararius/casco-job-interview:latest
    volumes:
    - ./:/app:delegated
    - ~/.composer/cache:/composer/cache:delegated
    networks:
    - interview

  pubsub:
    build:
      context: docker/emulator
      target: pubsub
    networks:
    - interview

  firestore:
    build:
      context: docker/emulator
      target: firestore
    networks:
    - interview

networks:
  interview:
    name: interview
