parameters:
  pubsub.imported_listings.topic: 'imported-listings'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Google\Cloud\Firestore\FirestoreClient:
    factory: 'App\GoogleCloud\FirestoreFactory::create'
    arguments:
      $projectId: '%env(GOOGLE_CLOUD_PROJECT)%'

  Google\Cloud\PubSub\PubSubClient:
    factory: 'App\GoogleCloud\PubSubFactory::client'
    arguments:
      $projectId: '%env(GOOGLE_CLOUD_PROJECT)%'

  pubsub.topic.imported_listings:
    class: Google\Cloud\PubSub\Topic
    factory: 'App\GoogleCloud\PubSubFactory::topic'
    arguments:
      $name: '%pubsub.imported_listings.topic%'
    tags: ['cloud.pubsub.topic']

  pubsub.subscription.process_imported_listings:
    class: App\GoogleCloud\Subscription
    factory: 'App\GoogleCloud\PubSubFactory::subscription'
    arguments:
      $topic: '@pubsub.topic.imported_listings'
      $name: 'process-imported-listings'
    tags: ['cloud.pubsub.subscription']

  App\ImportListingsCommand:
  App\ProcessListingsCommand:
  App\ShowListingsCommand:
