---
name: Docker images

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2.10.2
      id: filter
      with:
        filters: |
          docker:
            - 'docker/**'

  build:
    runs-on: ubuntu-latest
    needs: [init]
    if: needs.init.outputs.docker == 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: |
        docker build . -f docker/php/base/Dockerfile --tag ghcr.io/pararius/php-fpm-grpc:latest --target php
    - name: Publish image
      run: |
        docker push ghcr.io/pararius/php-fpm-grpc:latest
